# Generated by Django 4.2.1 on 2023-05-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.CharField(choices=[('', 'Select a location'), ('Panglao-Airport', 'Panglao-Airport'), ('Tagbilaran-Seaport', 'Tagbilaran-Seaport'), ('Hotel Pick-up', 'Hotel Pick-up')], max_length=100),
        ),
    ]
