# Generated by Django 4.2.1 on 2023-05-22 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reservation',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='rentalApp.reservation'),
            preserve_default=False,
        ),
    ]
