# Generated by Django 4.2.1 on 2023-05-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0007_alter_client_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reservation',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.reservation'),
        ),
    ]
