# Generated by Django 4.2.1 on 2023-05-23 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0015_motorcycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='motorcycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.motorcycle'),
        ),
    ]
