# Generated by Django 4.2.1 on 2023-05-24 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0017_car_count_motorcycle_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='count',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='count',
        ),
    ]
