# Generated by Django 4.2.1 on 2023-05-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0018_remove_car_count_remove_motorcycle_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
