# Generated by Django 4.2.1 on 2023-05-24 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0019_car_is_reserved_motorcycle_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.reservation'),
        ),
    ]
