# Generated by Django 4.2.1 on 2023-05-24 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0020_alter_client_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.reservation'),
        ),
    ]
