# Generated by Django 4.2.1 on 2023-05-24 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0021_car_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='car',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='is_reserved',
        ),
        migrations.AlterField(
            model_name='client',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.reservation'),
        ),
    ]
