# Generated by Django 4.2.1 on 2023-05-28 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0022_remove_car_is_reserved_remove_car_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_no',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$')]),
        ),
    ]
