# Generated by Django 4.2.1 on 2023-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0023_feedback_alter_client_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
