# Generated by Django 4.2.1 on 2023-05-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0026_client_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='car',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
    ]
