# Generated by Django 4.2.1 on 2023-05-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0027_remove_car_counter_remove_car_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
