# Generated by Django 4.2.1 on 2023-05-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0030_client_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='completed',
        ),
    ]
