# Generated by Django 4.2.1 on 2023-05-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0031_remove_client_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
