# Generated by Django 4.2.1 on 2023-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0033_remove_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
