# Generated by Django 4.2.1 on 2023-05-29 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0034_client_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pending',
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentalApp.reservation')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rentalApp.reservationstatus'),
        ),
    ]
