# Generated by Django 4.2.1 on 2023-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0038_client_completed_client_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
