# Generated by Django 4.2.1 on 2023-05-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0039_motorcycle_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
