# Generated by Django 4.2.1 on 2023-05-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0040_client_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='client',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pending',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rentalApp.client')),
            ],
        ),
    ]
