# Generated by Django 4.2.1 on 2023-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalApp', '0041_remove_client_completed_remove_client_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
